### ISSUE TITLE
ADDING ANALYSIS OF INJURIES

### ISSUE THREAD

**Issue by Swytah** [kabaddiPy/kabaddiPy#12]
HI! @sanjay-kv I AM SWETA THIRD YEAR STUDENT
WE CAN ADD ANALYSIS OF INJURIES WHICH WAS DONE FROM PLAYING THE KABBADI AND WE CAN ADD VISUAL'S OF CHARTS SHOWING THE PARTICIPANT OF THE PLAYERS AND HOW MANY HAVE WON THE GAME.

**Comment by annimukherjee** [comment]
Hi @Swytah

Nice Idea! Could you please layout a concrete plan with links that tell me exactly how you plan to do this?
Where will you get the data from?
What functions will you write?
How do you plan to do all of this while still making sure that your code fits into our code-base?

Happy to have a discussion :)

**Comment by annimukherjee** [comment]
Hi, since you didn't respond @Swytah I'm closing this issue!

Cheers
