### ISSUE TITLE
Adding a metrices table

### ISSUE THREAD

**Issue by Aman-G-upta** [kabaddiPy/kabaddiPy#37]
Adding a metrices table 
Adding a program section
![Screenshot 2024-10-26 185138](https://github.com/user-attachments/assets/c8e354f3-e70d-4483-ad71-02fbf92f751e)
Please assign me under this issue @kabaddiPY

**Comment by chetlasrijith** [comment]
Can i be assigned to this

**Comment by annimukherjee** [comment]
We don't need this.
