### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by KiranBaliga** [kabaddiPy/kabaddiPy#9]
I would like to add a code of conduct developed for your repository. Please let me know if it is okay to proceed. Please assign to me and add GSSoC24 Ext labels.

**Comment by annimukherjee** [comment]
How would this be different from `CONTRIBUTING.md`?

**Comment by ghost** [comment]
@annimukherjee contributing.md provides guidelines for people who want to contribute to the project but codeofconduct.md sets expectations for behavior in the community surrounding the project.

**Comment by ghost** [comment]
@annimukherjee Thank you. Please assign level1 and GSSoC24-Ext labels while I work on creating the file for the repo! 🙏

**Comment by annimukherjee** [comment]
Sure! 
Please draft a CODE_OF_CONDUCT.md ([inspiration](https://github.com/probot/template/blob/master/CODE_OF_CONDUCT.md))

**Comment by ghost** [comment]
@annimukherjee Please review the PR. Your feedback is highly appreciated. Please add level1 and GSSoC24 labels to the PR. Thank you!
